#
# Dependabot configuration
#

# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Maintain dependencies for NuGet.
  - package-ecosystem: nuget
    directory: '/'
    schedule:
      interval: daily
    labels:
      - dependencies
    reviewers:
      - microsoft/psrule

  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    labels:
      - 'ci-quality'
    reviewers:
      - 'microsoft/psrule'

  # Maintain dependencies for npm.
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    labels:
      - 'dependencies'
    reviewers:
      - 'microsoft/psrule'

 # Maintain dev containers.
  - package-ecosystem: devcontainers
    directory: '/'
    schedule:
      interval: weekly
